-- Generated by generate_curated_otc_sql.py at 2026-05-10T08:07:15+00:00
-- Source CSV: data/atc/curated_otc_starter.csv
-- atc_source tag: curated-otc-2026-05
-- Inserts 54 curated OTC rows.
-- Run AFTER migration 007_curated_otc_supplement.sql.
-- Idempotent (ON CONFLICT nappi_code DO UPDATE).

BEGIN;

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DISPRIN-001', 'Disprin', 'acetylsalicylic acid', 'acetylsalicylic acid',
    'S0', '300mg', 'tablet',
    'N02BA01', 'acetylsalicylic acid', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DISPRIN-002', 'Disprin Extra', 'acetylsalicylic acid', 'acetylsalicylic acid',
    'S0', '500mg', 'tablet',
    'N02BA01', 'acetylsalicylic acid', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-PANADO-001', 'Panado', 'paracetamol', 'paracetamol',
    'S0', '500mg', 'tablet',
    'N02BE01', 'paracetamol', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-PANADO-002', 'Panado Syrup', 'paracetamol', 'paracetamol',
    'S0', '120mg/5ml', 'syrup',
    'N02BE01', 'paracetamol', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CALPOL-001', 'Calpol Infant Syrup', 'paracetamol', 'paracetamol',
    'S0', '120mg/5ml', 'syrup',
    'N02BE01', 'paracetamol', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CALPOL-002', 'Calpol Six Plus', 'paracetamol', 'paracetamol',
    'S0', '250mg/5ml', 'syrup',
    'N02BE01', 'paracetamol', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-COMPRAL-001', 'Compral', 'paracetamol+caffeine', 'paracetamol+caffeine',
    'S0', '500mg+65mg', 'tablet',
    'N02BE51', 'paracetamol, combinations excl. psycholeptics', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-GRANDPA-001', 'Grandpa Headache Powder', 'paracetamol+aspirin+caffeine', 'paracetamol+aspirin+caffeine',
    'S1', '500mg+300mg+30mg', 'powder',
    'N02BE51', 'paracetamol, combinations excl. psycholeptics', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-MYBULEN-001', 'Mybulen', 'ibuprofen+paracetamol+codeine', 'ibuprofen+paracetamol+codeine',
    'S5', '200mg+250mg+10mg', 'tablet',
    'M01AE51', 'ibuprofen, combinations', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-NUROFEN-001', 'Nurofen', 'ibuprofen', 'ibuprofen',
    'S1', '200mg', 'tablet',
    'M01AE01', 'ibuprofen', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-VOLTAREN-001', 'Voltaren Emulgel', 'diclofenac', 'diclofenac diethylamine',
    'S2', '1%', 'gel',
    'M02AA15', 'diclofenac', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DEMAZIN-001', 'Demazin', 'chlorphenamine+phenylephrine', 'chlorphenamine maleate+phenylephrine hcl',
    'S2', '2mg+10mg/5ml', 'syrup',
    'R01BA53', 'phenylephrine, combinations', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DEMAZIN-002', 'Demazin Cold and Flu', 'chlorphenamine+phenylephrine+paracetamol', 'chlorphenamine+phenylephrine+paracetamol',
    'S2', NULL, 'tablet',
    'R05X', 'OTHER COLD PREPARATIONS', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-MEDLEMON-001', 'Med-Lemon', 'paracetamol+phenylephrine+chlorpheniramine+ascorbic acid', 'paracetamol+phenylephrine+chlorpheniramine+ascorbic acid',
    'S0', NULL, 'sachet powder',
    'N02BE51', 'paracetamol, combinations excl. psycholeptics', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-SINUTAB-001', 'Sinutab', 'paracetamol+pseudoephedrine', 'paracetamol+pseudoephedrine',
    'S2', '500mg+30mg', 'tablet',
    'N02BE51', 'paracetamol, combinations excl. psycholeptics', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-LINCTAGON-001', 'Linctagon Junior', 'zinc+vitamin C+pelargonium', 'zinc+ascorbic acid+pelargonium sidoides',
    'S0', NULL, 'syrup',
    'V03A', 'ALL OTHER THERAPEUTIC PRODUCTS', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ACC-001', 'ACC 200', 'acetylcysteine', 'acetylcysteine',
    'S2', '200mg', 'effervescent tablet',
    'R05CB01', 'acetylcysteine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-BISOLVON-001', 'Bisolvon', 'bromhexine', 'bromhexine hydrochloride',
    'S2', '8mg', 'tablet',
    'R05CB02', 'bromhexine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-BENYLIN-001', 'Benylin Wet Cough', 'guaifenesin+diphenhydramine', 'guaifenesin+diphenhydramine',
    'S2', NULL, 'syrup',
    'R05X', 'OTHER COLD PREPARATIONS', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-STREPSILS-001', 'Strepsils', 'amylmetacresol+dichlorobenzyl alcohol', 'amylmetacresol+2 4-dichlorobenzyl alcohol',
    'S0', NULL, 'lozenge',
    'R02AA20', 'various', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CEPACOL-001', 'Cepacol', 'cetylpyridinium+benzocaine', 'cetylpyridinium chloride+benzocaine',
    'S0', NULL, 'lozenge',
    'R02AA06', 'cetylpyridinium', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ZYRTEC-001', 'Zyrtec', 'cetirizine', 'cetirizine hydrochloride',
    'S2', '10mg', 'tablet',
    'R06AE07', 'cetirizine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-TEXA-001', 'Texa', 'loratadine', 'loratadine',
    'S2', '10mg', 'tablet',
    'R06AX13', 'loratadine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-TELFAST-001', 'Telfast', 'fexofenadine', 'fexofenadine hydrochloride',
    'S2', '180mg', 'tablet',
    'R06AX26', 'fexofenadine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ALLECET-001', 'Allecet', 'cetirizine', 'cetirizine',
    'S2', '10mg', 'tablet',
    'R06AE07', 'cetirizine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-BUSCOPAN-001', 'Buscopan', 'hyoscine butylbromide', 'hyoscine butylbromide',
    'S2', '10mg', 'tablet',
    'A03BB01', 'butylscopolamine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ENO-001', 'Eno', 'sodium bicarbonate+citric acid+sodium carbonate', 'sodium bicarbonate+citric acid+sodium carbonate',
    'S0', NULL, 'sachet powder',
    'A02AH', 'Antacids with sodium bicarbonate', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-RENNIE-001', 'Rennie', 'calcium carbonate+magnesium carbonate', 'calcium carbonate+magnesium carbonate',
    'S0', NULL, 'chewable tablet',
    'A02AD01', 'ordinary salt combinations', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-MAALOX-001', 'Maalox', 'aluminium hydroxide+magnesium hydroxide', 'aluminium hydroxide+magnesium hydroxide',
    'S0', NULL, 'suspension',
    'A02AD01', 'ordinary salt combinations', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-GAVISCON-001', 'Gaviscon', 'sodium alginate+sodium bicarbonate', 'sodium alginate+sodium bicarbonate+calcium carbonate',
    'S0', NULL, 'suspension',
    'A02BX13', 'alginic acid', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-IMODIUM-001', 'Imodium', 'loperamide', 'loperamide hydrochloride',
    'S2', '2mg', 'capsule',
    'A07DA03', 'loperamide', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ADCO-BILOSEC-001', 'Adco-Bilosec OTC', 'omeprazole', 'omeprazole',
    'S2', '20mg', 'capsule',
    'A02BC01', 'omeprazole', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-REUTERINA-001', 'Reuterina', 'Lactobacillus reuteri', 'Lactobacillus reuteri DSM 17938',
    'S0', NULL, 'drops',
    'A07FA', 'ANTIDIARRHEAL MICROORGANISMS', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-BIOPLUS-001', 'Bioplus', 'caffeine+vitamins', 'caffeine+thiamine+riboflavin+nicotinamide+pyridoxine+vitamin B12',
    'S0', NULL, 'syrup',
    'A13A', 'TONICS', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-BEROCCA-001', 'Berocca', 'B-complex+vitamin C', 'thiamine+riboflavin+nicotinamide+B6+B12+folic acid+vitamin C+pantothenic acid+biotin+calcium+magnesium+zinc',
    'S0', NULL, 'effervescent tablet',
    'A11JC', 'Vitamins, other combinations', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CENTRUM-001', 'Centrum Adults', 'multivitamin', 'multivitamins+minerals',
    'S0', NULL, 'tablet',
    'A11AA04', 'multivitamins and trace elements', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-VITAMINC-001', 'Vitamin C 500', 'ascorbic acid', 'ascorbic acid',
    'S0', '500mg', 'tablet',
    'A11GA01', 'ascorbic acid (vit C)', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-VITAMINB12-001', 'Vitamin B12 1000', 'cyanocobalamin', 'cyanocobalamin',
    'S0', '1000mcg', 'tablet',
    'B03BA01', 'cyanocobalamin', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CALCIMAX-001', 'Calcimax', 'calcium carbonate+vitamin D3', 'calcium carbonate+cholecalciferol',
    'S0', NULL, 'tablet',
    'A12AX', 'Calcium, combinations with vitamin D and/or other drugs', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-MAGOX-001', 'Slow-Mag', 'magnesium chloride', 'magnesium chloride+calcium lactate',
    'S0', NULL, 'tablet',
    'A12CC01', 'magnesium chloride', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-IBROFEM-001', 'Ibrofem', 'ibuprofen', 'ibuprofen',
    'S1', '200mg', 'tablet',
    'M01AE01', 'ibuprofen', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DEEPHEAT-001', 'Deep Heat', 'methyl salicylate+menthol+eucalyptus', 'methyl salicylate+menthol+eucalyptus oil',
    'S0', NULL, 'cream',
    'M02AC', 'Preparations with salicylic acid derivatives', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ARNICA-001', 'Arnica Cream', 'arnica montana', 'arnica montana extract',
    'S0', NULL, 'cream',
    'M02AX10', 'various', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-ANTABAX-001', 'Antabax', 'chlorhexidine', 'chlorhexidine gluconate',
    'S0', '4%', 'liquid',
    'D08AC02', 'chlorhexidine', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DETTOL-001', 'Dettol Antiseptic', 'chloroxylenol', 'chloroxylenol',
    'S0', '4.8%', 'liquid',
    'D08AE05', 'chloroxylenol', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-SAVLON-001', 'Savlon Antiseptic', 'chlorhexidine+cetrimide', 'chlorhexidine gluconate+cetrimide',
    'S0', NULL, 'liquid',
    'D08AC52', 'chlorhexidine, combinations', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-SUDOCREM-001', 'Sudocrem', 'zinc oxide+benzyl alcohol+benzyl benzoate', 'zinc oxide+benzyl alcohol+benzyl benzoate+benzyl cinnamate+lanolin',
    'S0', NULL, 'cream',
    'D02AB', 'Zinc products', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-BACTROBAN-001', 'Bactroban', 'mupirocin', 'mupirocin',
    'S2', '2%', 'ointment',
    'D06AX09', 'mupirocin', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CANDID-001', 'Candid', 'clotrimazole', 'clotrimazole',
    'S2', '1%', 'cream',
    'D01AC01', 'clotrimazole', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-CANESTEN-001', 'Canesten', 'clotrimazole', 'clotrimazole',
    'S2', '1%', 'cream',
    'D01AC01', 'clotrimazole', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-DAKTARIN-001', 'Daktarin', 'miconazole', 'miconazole nitrate',
    'S2', '2%', 'cream',
    'D01AC02', 'miconazole', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-PROBANE-001', 'Probane', 'zinc oxide', 'zinc oxide',
    'S0', NULL, 'cream',
    'D02AB', 'Zinc products', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-COVID-VITC-001', 'Vitamin C 1000', 'ascorbic acid', 'ascorbic acid',
    'S0', '1000mg', 'tablet',
    'A11GA01', 'ascorbic acid (vit C)', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

INSERT INTO nappi_codes (
    nappi_code, brand_name, generic_name, ingredients,
    schedule, strength, dosage_form,
    atc_code, atc_class_desc, atc_match_method, atc_source,
    atc_matched_at, data_source, status,
    created_at, updated_at
) VALUES (
    'CURATED-OMEGA3-001', 'Omega-3', 'omega-3 fatty acids', 'fish oil omega-3',
    'S0', '1000mg', 'capsule',
    'C10AX06', 'omega-3 triglycerides incl. other esters and acids', 'manual', 'curated-otc-2026-05',
    NOW(), 'curated', 'active',
    NOW(), NOW()
)
ON CONFLICT (nappi_code) DO UPDATE SET
    brand_name       = EXCLUDED.brand_name,
    generic_name     = EXCLUDED.generic_name,
    ingredients      = EXCLUDED.ingredients,
    schedule         = EXCLUDED.schedule,
    strength         = EXCLUDED.strength,
    dosage_form      = EXCLUDED.dosage_form,
    atc_code         = EXCLUDED.atc_code,
    atc_class_desc   = EXCLUDED.atc_class_desc,
    atc_match_method = EXCLUDED.atc_match_method,
    atc_source       = EXCLUDED.atc_source,
    atc_matched_at   = EXCLUDED.atc_matched_at,
    data_source      = EXCLUDED.data_source,
    updated_at       = NOW();

COMMIT;
