"""
Read the curated OTC CSV, validate every row, and emit an INSERT SQL file
suitable for pasting into the Supabase SQL editor.

Usage:
    .venv/bin/python scripts/generate_curated_otc_sql.py \\
        --csv data/atc/curated_otc_starter.csv \\
        --out data/atc/run_2026-05-10/007_curated_otc_data.sql

Idempotent: uses ON CONFLICT (nappi_code) DO UPDATE so re-running the same
SQL just refreshes the row. Re-runs preserve created_at on existing rows
(only updated_at is bumped).
"""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from scripts import atc_backfill as atc  # noqa: E402

DEFAULT_ATC = HERE.parent / "data" / "atc" / "WHO_ATC-DDD_2026-04-25.csv"
ATC_SOURCE = "curated-otc-2026-05"
DATA_SOURCE = "curated"
MATCH_METHOD = "manual"


def _esc(s: str | None) -> str:
    """SQL string-literal escape; returns NULL for empty/None."""
    if s is None:
        return "NULL"
    s = str(s).strip()
    if not s:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--csv", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--atc-csv", type=Path, default=DEFAULT_ATC)
    args = p.parse_args()

    by_code, _ = atc.load_atc(args.atc_csv)

    rows: list[dict[str, str]] = []
    with args.csv.open(newline="", encoding="utf-8") as f:
        rdr = csv.DictReader(f)
        for r in rdr:
            rows.append({k: (v or "").strip() for k, v in r.items()})

    # Pre-flight: every row's atc_code must exist in WHO. Bail early if not.
    bad: list[str] = []
    seen_ids: set[str] = set()
    for i, r in enumerate(rows, 1):
        cid = r["curated_id"]
        if not cid:
            bad.append(f"row {i}: missing curated_id")
            continue
        if cid in seen_ids:
            bad.append(f"row {i}: duplicate curated_id '{cid}'")
        seen_ids.add(cid)
        if r["atc_code"] and r["atc_code"] not in by_code:
            bad.append(
                f"row {i} ({cid}): atc_code '{r['atc_code']}' not in WHO index")
    if bad:
        for b in bad:
            print(f"  ✗ {b}", file=sys.stderr)
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    now_iso = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")

    with args.out.open("w", encoding="utf-8") as f:
        f.write(
            f"-- Generated by generate_curated_otc_sql.py at {now_iso}\n"
            f"-- Source CSV: {args.csv}\n"
            f"-- atc_source tag: {ATC_SOURCE}\n"
            f"-- Inserts {len(rows)} curated OTC rows.\n"
            f"-- Run AFTER migration 007_curated_otc_supplement.sql.\n"
            f"-- Idempotent (ON CONFLICT nappi_code DO UPDATE).\n\n"
            "BEGIN;\n\n"
        )
        for r in rows:
            f.write(
                "INSERT INTO nappi_codes (\n"
                "    nappi_code, brand_name, generic_name, ingredients,\n"
                "    schedule, strength, dosage_form,\n"
                "    atc_code, atc_class_desc, atc_match_method, atc_source,\n"
                "    atc_matched_at, data_source, status,\n"
                "    created_at, updated_at\n"
                ") VALUES (\n"
                f"    {_esc(r['curated_id'])}, {_esc(r['brand_name'])}, "
                f"{_esc(r['generic_name'])}, {_esc(r['ingredients'])},\n"
                f"    {_esc(r['schedule'])}, {_esc(r['strength'])}, "
                f"{_esc(r['dosage_form'])},\n"
                f"    {_esc(r['atc_code'])}, {_esc(r['atc_class_desc'])}, "
                f"{_esc(MATCH_METHOD)}, {_esc(ATC_SOURCE)},\n"
                f"    NOW(), {_esc(DATA_SOURCE)}, 'active',\n"
                f"    NOW(), NOW()\n"
                ")\n"
                "ON CONFLICT (nappi_code) DO UPDATE SET\n"
                "    brand_name       = EXCLUDED.brand_name,\n"
                "    generic_name     = EXCLUDED.generic_name,\n"
                "    ingredients      = EXCLUDED.ingredients,\n"
                "    schedule         = EXCLUDED.schedule,\n"
                "    strength         = EXCLUDED.strength,\n"
                "    dosage_form      = EXCLUDED.dosage_form,\n"
                "    atc_code         = EXCLUDED.atc_code,\n"
                "    atc_class_desc   = EXCLUDED.atc_class_desc,\n"
                "    atc_match_method = EXCLUDED.atc_match_method,\n"
                "    atc_source       = EXCLUDED.atc_source,\n"
                "    atc_matched_at   = EXCLUDED.atc_matched_at,\n"
                "    data_source      = EXCLUDED.data_source,\n"
                "    updated_at       = NOW();\n\n"
            )
        f.write("COMMIT;\n")

    print(f"Wrote {len(rows)} INSERTs → {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
