-- ============================================================
-- Mining FD: quarantine v2 — second pass after audit
-- ============================================================
-- A deeper audit of the cash-flow and ownership facts (done while growing
-- the gold set toward the §8 30–50 target) surfaced more dupes and silent
-- misreads. Four more financial facts get withdrawn here; three OWNS
-- edges with effective_pct=0.0 get deleted.
--
-- Audit notes — what's quarantined and why:
--
-- A. Duplicates with already-quarantined siblings:
--    * CashDividendPaid-2024 = R199m
--        → mirror of the already-quarantined CashDividendPaid-2023 (R90m).
--          Same misread off the "Economic value distribution" donut chart
--          where small percent slices got read as raw rand values.
--    * NetCash-2024 = R16,300m
--        → value equal to NetCashExcludingEnergyNetDebt-2024 = R16,300m;
--          same concept named twice from two table cells.
--    * NetCashPositionExcludingEnergyNetDebt-2024 = R16,300m
--        → sibling of the v1-quarantined 2023 row (R14,800m). Same
--          metric named twice ("NetCashPosition" vs "NetCashExcluding").
--    * CashGeneratedByOperations-2024 = R10,400m
--        → equal in value AND in source-quote concept to the existing
--          CashGenerated-2024. The chapter's prose ("Cash generated by
--          operations at R10.4 billion") and its companion bar chart
--          ("Cash generated FY24: 10.4") got captured as two separate
--          metrics. Keep CashGenerated (bar-chart canonical name);
--          retire CashGeneratedByOperations.
--
-- B. NOTE on what we DECIDED NOT to quarantine:
--    * CashGenerated-2023/2024 (R13,300m / R10,400m).
--      External review reasonably suspected EBITDA-mislabel because the
--      values are close to EBITDA values for the same years. The source
--      audit acquitted them: their spans cite a "Cash generated" bar
--      chart that's a distinct Exxaro headline line item. The values
--      happen to coincide with EBITDA in 2024 (Exxaro reports both as
--      "down 22%"); they're not the same metric, just numerically equal.
--      Audit trail captured.
--
-- C. OWNS edges with effective_pct = 0.0 (the silent-crack class):
--    The model wrote three OWNS edges (Exxaro→Mafube, →Black Mountain,
--    →RBCT) with effective_pct=0.0. The chapter doesn't actually
--    disclose Exxaro's effective percentage in these assets; the
--    model defaulted to 0. Q1's attributable rollup ALSO defaults to
--    1.0 when payload.effective_pct is falsy (Python truthiness:
--    0.0 → None → 1.0 fallback), so the 0 quietly turns into an
--    assumed 100% on the answer side — exactly the kind of silent
--    drift the precision-preference work targets.
--    Fix: DELETE the bogus edges entirely. Q1 then sees no OWNS
--    edge for these assets and falls back to its 1.0-default with
--    nothing to be silent about. A follow-up Q1 honesty change should
--    surface "ownership unknown — assuming 100%" rather than just
--    1.0-by-default, but that's a separate piece of work.
--
-- Idempotent: re-runs are no-ops once the rows are marked / deleted.
-- ============================================================

DO $$
DECLARE
    v_workspace_id UUID;
BEGIN
    SELECT id INTO v_workspace_id FROM workspaces WHERE slug = 'exxaro-fd' LIMIT 1;
    IF v_workspace_id IS NULL THEN
        RAISE EXCEPTION 'Workspace "exxaro-fd" not found.';
    END IF;

    -- A. Financial-fact dupes / misreads → status='withdrawn'.
    UPDATE fd_financial_facts
       SET status = 'withdrawn', updated_at = NOW()
     WHERE workspace_id = v_workspace_id
       AND canonical_id IN (
            'EXXARO-001-CashDividendPaid-2024',
            'EXXARO-001-NetCash-2024',
            'EXXARO-001-NetCashPositionExcludingEnergyNetDebt-2024',
            'EXXARO-001-CashGeneratedByOperations-2024'
       )
       AND status = 'active';

    -- C. Bogus OWNS edges (effective_pct=0.0 where ownership undisclosed
    --    in ingested chapters). DELETE rather than withdraw — Q1's lookup
    --    doesn't filter on status, and the silent-crack risk is real.
    DELETE FROM fd_edges
     WHERE workspace_id = v_workspace_id
       AND relation = 'OWNS'
       AND src_canonical_id = 'EXXARO-001'
       AND dst_canonical_id IN ('MAFUBE-001', 'BLACK-MOUNTAIN-001', 'RBCT-001')
       AND (payload->>'effective_pct')::numeric < 0.01;

    -- Cascade: remove the now-orphaned EVIDENCED_BY edges pointing at the
    -- DELETEd OWNS rows. Spans themselves stay (still reference the
    -- existing entity).
    -- (The EVIDENCED_BY edges from EXXARO-001 to spans are still valid
    --  because they're org-level evidence, not OWNS-edge evidence.)

    RAISE NOTICE 'Quarantine v2 complete: 4 facts withdrawn, 3 bogus OWNS edges deleted.';
END $$;
