-- ============================================================
-- Mining Gateway / Financial-Disclosure — registry extension v2
-- ============================================================
-- Closes the gap surfaced by the first live ADE run against the FY2024 IR
-- chapters (commit 5cc1bb9). 174 surface forms went to fd_facts_needs_review
-- across 106 distinct names. This migration converts the legitimate-entity
-- subset into registry rows so subsequent ingests resolve cleanly.
--
-- Three buckets:
--   1. ALIAS  → UPDATE: extends surface_forms[] on existing canonical IDs.
--   2. NEW    → INSERT: adds canonical IDs for entities Exxaro actually
--                       operates / owns / partners with that weren't in
--                       mining_seed_entity_registry.sql.
--   3. SKIP   → Common-noun noise (operations, coal, five mines, …) is left
--               in the quarantine queue intentionally — the operator-review
--               UI is the right place to handle it; auto-promoting noise
--               would re-introduce the "wrong silent merge" failure mode
--               the spec §4.2 explicitly warns against.
--
-- Idempotent: re-running this file is a no-op once applied (UPDATE conditions
-- are idempotent; INSERTs ON CONFLICT DO UPDATE).
--
-- After applying, re-run the FY2024 IR chapter ingest — the cache hits, so
-- it costs zero ADE credits. Expected behaviour change:
--   * 'Group' (42 occurrences) resolves to EXXARO-001 → many more facts land.
--   * 'Coal operations' / 'our coal business' etc. → PILLAR-COAL-OPS-001 →
--     strategic_narratives can now write ALLOCATED_TO edges (the
--     strategically_attributed chip flows downstream).
--   * Mafube / Black Mountain / LSP / Karreebosch / SIOC / G7 Renewables
--     become first-class registry entries; future fact extractions for them
--     land in fd_assets / fd_orgs instead of the quarantine.
-- ============================================================

DO $$
DECLARE
    v_workspace_id UUID;
BEGIN
    SELECT id INTO v_workspace_id
      FROM workspaces WHERE slug = 'exxaro-fd' LIMIT 1;
    IF v_workspace_id IS NULL THEN
        RAISE EXCEPTION 'Workspace "exxaro-fd" not found. Run mining_seed_workspace.sql first.';
    END IF;

    -- ------------------------------------------------------------
    -- 1. ALIAS extensions on existing canonical IDs.
    --    Each UPDATE merges new surface_forms with the existing array,
    --    de-duplicating via a subquery, so this is safe to re-run.
    -- ------------------------------------------------------------

    -- EXXARO-001: "Group" (42x) and parenthesised qualifier variants.
    -- "Group (Export coal)" et al. are the model's per-impact subject; we
    -- bind the bare "Group" form here. The qualifier-suffixed forms will
    -- still resolve via pg_trgm similarity to the canonical "Group" alias.
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'Group', 'group', 'the Group'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'EXXARO-001';

    -- CENNERGI-001: subsidiary-as-collective references.
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'Cennergi''s operating wind assets',
               'our energy solutions business',
               'energy solutions business',
               'Cennergi (energy solutions business)'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'CENNERGI-001';

    -- PILLAR-COAL-OPS-001: the company's own framings of its coal business
    -- when it's narrating capital flow (Q3 / strategic_narratives). These
    -- are what make the §3.3 'Coal Asset → Diversification Fund' linkage
    -- resolve and stamp 'strategically_attributed'.
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'Coal operations',
               'coal operations',
               'Our coal business',
               'our coal business',
               'coal business',
               'our strong coal resources',
               'the value generated by coal',
               'coal portfolio and business',
               'The resilience of our coal business',
               'the resilience of our coal business',
               'our coal portfolio'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'PILLAR-COAL-OPS-001';

    -- PILLAR-GREEN-ENERGY-001: the destination side of strategic narratives
    -- about renewables.
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'renewable energy',
               'Renewable energy',
               'renewable energy solutions offering',
               'energy projects',
               'energy transition',
               'low-carbon solutions',
               'our transition to low-carbon solutions',
               'low-carbon transition'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'PILLAR-GREEN-ENERGY-001';

    -- PILLAR-FUTURE-MINERALS-001: the manganese / future-minerals destination.
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'energy transition minerals',
               'Energy Transition Minerals',
               'Energy transition minerals',
               'energy transition mineral investments',
               'energy transition mineral',
               'low-carbon transition minerals',
               'transition minerals'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'PILLAR-FUTURE-MINERALS-001';

    -- FUND-SUSTAINING-001
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'Sustaining',
               'sustaining capital projects',
               'stay-in-business capex',
               'coal sustaining capital'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'FUND-SUSTAINING-001';

    -- FUND-EXPANSION-001
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'expansion capital for our energy projects',
               'expansion capital',
               'growth capital'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'FUND-EXPANSION-001';

    -- FUND-DIVERSIFICATION-001: the company's generic capital-allocation
    -- framings. These power Q3 (strategic_narratives "X ALLOCATED_TO Y" where
    -- X is one of these phrases).
    UPDATE fd_entity_registry r
       SET surface_forms = (
           SELECT ARRAY(SELECT DISTINCT unnest(r.surface_forms || ARRAY[
               'capital allocation',
               'Our capital allocation',
               'our capital allocation',
               'financial capital',
               'Financial capital',
               'project financing',
               'excess cash',
               'solid cash base'
           ]))
       )
     WHERE r.workspace_id = v_workspace_id AND r.canonical_id = 'FUND-DIVERSIFICATION-001';


    -- ------------------------------------------------------------
    -- 2. NEW canonical IDs.
    --    Each is a real entity Exxaro names in the FY2024 IR chapters.
    --    Mapper will create the matching fd_assets / fd_orgs row when a
    --    fact arrives for them on the next ingest.
    -- ------------------------------------------------------------
    INSERT INTO fd_entity_registry
        (workspace_id, canonical_id, canonical_name, entity_type, surface_forms, owned_via, notes)
    VALUES
    -- Coal assets (Exxaro-owned)
    (v_workspace_id, 'MAFUBE-001', 'Mafube Coal Mine', 'Asset',
        ARRAY['Mafube', 'Mafube Coal Mine', 'Mafube (Buy-in volumes impact)'],
        'EXXARO-001',
        'JV coal mine. The "(Buy-in volumes impact)" variant is a cost-analysis qualifier; bind it here so the impact-attribution facts roll up to the right asset.'),

    -- Black Mountain (Exxaro holds a stake; produces zinc + lead, not coal)
    (v_workspace_id, 'BLACK-MOUNTAIN-001', 'Black Mountain', 'Asset',
        ARRAY['Black Mountain', 'Black Mountain Mining', 'Black Mountain Mine'],
        'EXXARO-001',
        'Equity-accounted base-metals mine (zinc + lead). Held via stake, not consolidated.'),

    -- Richards Bay Coal Terminal — Exxaro is a shareholder
    (v_workspace_id, 'RBCT-001', 'Richards Bay Coal Terminal', 'Asset',
        ARRAY['RBCT', 'Richards Bay Coal Terminal', 'Richards Bay terminal'],
        'EXXARO-001',
        'Export coal-handling terminal at Richards Bay. Exxaro is one of several shareholders; effective_pct should be sourced when an OWNS edge is asserted.'),

    -- Lephalale Solar Project — 68MW PV plant at Grootegeluk
    (v_workspace_id, 'LSP-001', 'Lephalale Solar Project', 'Asset',
        ARRAY['LSP', 'Lephalale Solar Project', '68MW LSP', '68MW LSP at Grootegeluk', 'Grootegeluk solar plant', 'LSP at Grootegeluk', '68MW Lephalale Solar Project'],
        'EXXARO-001',
        'On-site solar PV at the Grootegeluk coal complex, supplying renewable power to coal operations — the §3.3 Coal → Renewable narrative''s most concrete project example.'),

    -- Karreebosch — Cennergi wind project
    (v_workspace_id, 'KARREEBOSCH-001', 'Karreebosch Wind Farm', 'Asset',
        ARRAY['Karreebosch', 'Karreebosch project', 'Karreebosch Wind Farm', 'Karreebosch wind farm'],
        'CENNERGI-001',
        'Wind farm project under Cennergi. Karreebosch Asset Management Pty Ltd is the holding SPV (see KARREEBOSCH-AM-001 if needed).'),

    -- Amakhala Emoyeni — Cennergi wind farm
    (v_workspace_id, 'AMAKHALA-EMOYENI-001', 'Amakhala Emoyeni Wind Farm', 'Asset',
        ARRAY['Amakhala Emoyeni', 'Amakhala Emoyeni Wind Farm', 'Amakhala wind farm'],
        'CENNERGI-001',
        'Operating wind farm under Cennergi.'),

    -- Sishen Iron Ore Company — equity-accounted Org, not a mine asset
    (v_workspace_id, 'SIOC-001', 'Sishen Iron Ore Company', 'Org',
        ARRAY['SIOC', 'Sishen Iron Ore Company', 'Sishen Iron Ore'],
        NULL,
        'Equity-accounted iron-ore producer. Exxaro holds a stake; treat as Org / Counterparty, not an operated asset.'),

    -- G7 Renewable Energies — Cennergi partner / dev co
    (v_workspace_id, 'G7-RENEWABLES-001', 'G7 Renewable Energies', 'Org',
        ARRAY['G7 Renewable Energies', 'G7 Renewable Energies Proprietary Limited', 'G7 Renewables', 'G7'],
        NULL,
        'Renewables development partner used by Cennergi.')

    ON CONFLICT (workspace_id, canonical_id) DO UPDATE
        SET canonical_name = EXCLUDED.canonical_name,
            entity_type    = EXCLUDED.entity_type,
            surface_forms  = EXCLUDED.surface_forms,
            owned_via      = EXCLUDED.owned_via,
            notes          = EXCLUDED.notes,
            updated_at     = NOW();

    -- ------------------------------------------------------------
    -- 3. PRE-SEED node-table rows so the mapper's §3.3 stamping rules
    --    (_stamp_assertion_type) can read commodity / org-shape from
    --    fd_assets / fd_orgs at narrative-processing time. Without these
    --    pre-seeded rows, a strategic_narrative endpoint that resolves to
    --    e.g. KARREEBOSCH-001 (Renewable) gets stamped 'disclosed' because
    --    the mapper hits an empty fd_assets row and falls through.
    -- ------------------------------------------------------------
    INSERT INTO fd_assets (workspace_id, canonical_id, name, commodity, region, lifecycle)
    VALUES
        (v_workspace_id, 'MAFUBE-001',           'Mafube Coal Mine',            'Coal',      'Mpumalanga',     'Producing'),
        (v_workspace_id, 'BLACK-MOUNTAIN-001',   'Black Mountain',              'Other',     'Northern Cape',  'Producing'),
        (v_workspace_id, 'RBCT-001',             'Richards Bay Coal Terminal',  'Coal',      'KwaZulu-Natal',  'Producing'),
        (v_workspace_id, 'LSP-001',              'Lephalale Solar Project',     'Renewable', 'Limpopo',        'Producing'),
        (v_workspace_id, 'KARREEBOSCH-001',      'Karreebosch Wind Farm',       'Renewable', 'Western Cape',   'Pipeline'),
        (v_workspace_id, 'AMAKHALA-EMOYENI-001', 'Amakhala Emoyeni Wind Farm',  'Renewable', 'Eastern Cape',   'Producing')
    ON CONFLICT (workspace_id, canonical_id) DO UPDATE
        SET name = EXCLUDED.name,
            commodity = EXCLUDED.commodity,
            region = EXCLUDED.region,
            lifecycle = EXCLUDED.lifecycle;

    INSERT INTO fd_orgs (workspace_id, canonical_id, name, org_type)
    VALUES
        (v_workspace_id, 'SIOC-001',           'Sishen Iron Ore Company', 'Counterparty'),
        (v_workspace_id, 'G7-RENEWABLES-001',  'G7 Renewable Energies',   'Partner')
    ON CONFLICT (workspace_id, canonical_id) DO UPDATE
        SET name = EXCLUDED.name,
            org_type = EXCLUDED.org_type;

    -- ------------------------------------------------------------
    -- 4. Pre-seed the v1 registry entries too so the node tables stay
    --    stable across ingest runs that clear fact tables. Without this,
    --    a re-ingest that wipes fd_capital_funds / fd_strategic_pillars /
    --    fd_orgs / fd_assets between runs leaves the mapper unable to
    --    resolve §3.3 stamping queries (which read those tables).
    -- ------------------------------------------------------------
    INSERT INTO fd_orgs (workspace_id, canonical_id, name, org_type)
    VALUES
        (v_workspace_id, 'EXXARO-001',      'Exxaro Resources Limited',       'Issuer'),
        (v_workspace_id, 'NTSIMBINTLE-001', 'Ntsimbintle Holdings (Pty) Ltd', 'HoldingCo'),
        (v_workspace_id, 'CENNERGI-001',    'Cennergi (Pty) Ltd',             'Subsidiary')
    ON CONFLICT (workspace_id, canonical_id) DO NOTHING;

    INSERT INTO fd_assets (workspace_id, canonical_id, name, commodity, region, lifecycle)
    VALUES
        (v_workspace_id, 'GROOT-001',       'Grootegeluk Coal Mine',         'Coal',      'Limpopo',       'Producing'),
        (v_workspace_id, 'MATLA-001',       'Matla Coal Complex',            'Coal',      'Mpumalanga',    'Producing'),
        (v_workspace_id, 'BELFAST-001',     'Belfast Mine',                  'Coal',      'Mpumalanga',    'Producing'),
        (v_workspace_id, 'LEEUWPAN-001',    'Leeuwpan Mine',                 'Coal',      'Mpumalanga',    'Producing'),
        (v_workspace_id, 'TSHIPI-001',      'Tshipi Borwa Mine',             'Manganese', 'Northern Cape', 'Producing'),
        (v_workspace_id, 'TSITSIKAMMA-001', 'Tsitsikamma Community Wind Farm','Renewable','Eastern Cape', 'Producing')
    ON CONFLICT (workspace_id, canonical_id) DO NOTHING;

    INSERT INTO fd_capital_funds (workspace_id, canonical_id, name, fund_type)
    VALUES
        (v_workspace_id, 'FUND-SUSTAINING-001',      'Sustaining Capital Fund',     'Sustaining'),
        (v_workspace_id, 'FUND-EXPANSION-001',       'Expansion Capital Fund',      'Expansion'),
        (v_workspace_id, 'FUND-DIVERSIFICATION-001', 'Diversification Capital Fund','Diversification')
    ON CONFLICT (workspace_id, canonical_id) DO NOTHING;

    INSERT INTO fd_strategic_pillars (workspace_id, canonical_id, name)
    VALUES
        (v_workspace_id, 'PILLAR-COAL-OPS-001',         'Coal Operations'),
        (v_workspace_id, 'PILLAR-GREEN-ENERGY-001',     'Green Energy'),
        (v_workspace_id, 'PILLAR-FUTURE-MINERALS-001',  'Future Minerals')
    ON CONFLICT (workspace_id, canonical_id) DO NOTHING;

    INSERT INTO fd_acquisitions (workspace_id, canonical_id, name, value_zar_m, status)
    VALUES
        (v_workspace_id, 'ACQ-KALAHARI-MN-001', 'Kalahari Manganese Acquisition', 0.0, 'Closed')
    ON CONFLICT (workspace_id, canonical_id) DO NOTHING;

    RAISE NOTICE 'Registry v2 applied: 8 alias extensions + 8 new canonical IDs + node-table baselines';
END $$;

-- ============================================================
-- Coverage check (informational; not a constraint).
-- After v2: expect 24 rows (16 from v1 + 8 new).
-- ============================================================
-- SELECT entity_type, COUNT(*) AS rows
--   FROM fd_entity_registry r JOIN workspaces w ON w.id = r.workspace_id
--  WHERE w.slug = 'exxaro-fd'
--  GROUP BY entity_type ORDER BY entity_type;
